#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication surfaceFeatureExtract -includedAngle 150 -writeObj constant/triSurface/Obstacle.stl Obstacle
cp -r 0.org 0 > /dev/null 2>&1
runApplication snappyHexMesh -overwrite
runApplication setFields
runApplication $application

# ----------------------------------------------------------------- end-of-file
